/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "React Canvas Editor",
  "tagline": "A powerful, customizable React-based document editor for crafting and managing multi-page documents with ease.",
  "favicon": "img/mindfire.ico",
  "url": "https://mindfiredigital.github.io",
  "baseUrl": "/react-canvas-editor/",
  "organizationName": "mindfiredigital",
  "projectName": "react-canvas-editor",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/sanghamitrad/Documents/open-source/editor/react-canvas-editor/docusaurus/sidebars.js",
          "editUrl": "https://github.com/mindfiredigital/react-canvas-editor/tree/main/docusaurus/"
        },
        "theme": {
          "customCss": "/home/sanghamitrad/Documents/open-source/editor/react-canvas-editor/docusaurus/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "colorMode": {
      "defaultMode": "light",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "announcementBar": {
      "id": "npm_release",
      "content": "🎉 <b>v1.3.0</b> of <code>@mindfiredigital/canvas-editor</code> is live on npm — <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.npmjs.com/package/@mindfiredigital/canvas-editor\">view package</a>",
      "backgroundColor": "#1a1b2e",
      "textColor": "#ffffff",
      "isCloseable": true
    },
    "navbar": {
      "title": "React Canvas Editor",
      "logo": {
        "alt": "React Canvas Editor",
        "src": "img/logo.webp"
      },
      "items": [
        {
          "to": "/",
          "label": "Home",
          "position": "left"
        },
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Docs"
        },
        {
          "to": "/docs/Get-started/quickstart",
          "label": "Quick Start",
          "position": "left"
        },
        {
          "href": "https://www.npmjs.com/package/@mindfiredigital/canvas-editor",
          "label": "npm",
          "position": "right"
        },
        {
          "href": "https://github.com/mindfiredigital/react-canvas-editor",
          "className": "header-github-link",
          "aria-label": "GitHub repository",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/what-is-document-editor"
            },
            {
              "label": "Installation",
              "to": "/docs/Get-started/Installation"
            },
            {
              "label": "Quick Start",
              "to": "/docs/Get-started/quickstart"
            },
            {
              "label": "API Reference",
              "to": "/docs/references/dom-event"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/mindfiredigital/react-canvas-editor"
            },
            {
              "label": "npm",
              "href": "https://www.npmjs.com/package/@mindfiredigital/canvas-editor"
            },
            {
              "label": "Issues",
              "href": "https://github.com/mindfiredigital/react-canvas-editor/issues"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Release Notes",
              "to": "/docs/release/release-notes"
            },
            {
              "label": "Report an Issue",
              "href": "https://github.com/mindfiredigital/react-canvas-editor/issues"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Mindfire Digital LLP. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "tsx",
        "jsx"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
